---
name: Build on Arch Linux

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Sync AUR package with current version
        uses: pajlada/aur-sync-action@master
        with:
          package_name: chatterino7-git
          commit_username: chatterino7-ci
          commit_email: chatterino7-ci@pajlada.com
          ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
          dry_run: true
